In [24]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [25]:
# import raw data
df = pd.read_csv('13version.csv')
df.head(10)

,match_id,t1_champ1,t1_p1,t1_champ2,t1_p2,t1_champ3,t1_p3,t1_champ4,t1_p4,t1_champ5,...,t2_p1,t2_champ2,t2_p2,t2_champ3,t2_p3,t2_champ4,t2_p4,t2_champ5,t2_p5,t1_win
0,NA1_4648668472,Yone,TOP,Graves,JUNGLE,Swain,MIDDLE,Nilah,BOTTOM,Thresh,...,TOP,JarvanIV,JUNGLE,Lissandra,MIDDLE,Twitch,BOTTOM,Rakan,SUPPORT,1
1,NA1_4647203651,Shen,TOP,MonkeyKing,JUNGLE,Zed,MIDDLE,Zeri,BOTTOM,Senna,...,TOP,Udyr,JUNGLE,Renekton,MIDDLE,Lucian,BOTTOM,Milio,SUPPORT,1
2,NA1_4653989325,Camille,TOP,Karthus,JUNGLE,Viktor,MIDDLE,Jhin,BOTTOM,Thresh,...,TOP,JarvanIV,JUNGLE,Syndra,MIDDLE,Xayah,BOTTOM,Milio,SUPPORT,0
3,NA1_4645994436,Ornn,TOP,Vi,JUNGLE,Irelia,MIDDLE,Varus,BOTTOM,Janna,...,TOP,Kindred,JUNGLE,Neeko,MIDDLE,Ziggs,BOTTOM,Thresh,SUPPORT,1
4,NA1_4648099886,Kled,TOP,JarvanIV,JUNGLE,Yasuo,MIDDLE,Seraphine,BOTTOM,Zilean,...,TOP,Khazix,JUNGLE,Yone,MIDDLE,Xayah,BOTTOM,Xerath,SUPPORT,0
5,NA1_4652926620,Poppy,TOP,RekSai,JUNGLE,Ahri,MIDDLE,Jinx,BOTTOM,Thresh,...,TOP,Rengar,JUNGLE,Yone,MIDDLE,Zeri,BOTTOM,Yuumi,SUPPORT,0
6,NA1_4653056604,Chogath,TOP,MasterYi,JUNGLE,Malzahar,MIDDLE,Xayah,BOTTOM,Milio,...,TOP,Belveth,JUNGLE,Lissandra,MIDDLE,Twitch,BOTTOM,Janna,SUPPORT,1
7,NA1_4647316276,Camille,TOP,MasterYi,JUNGLE,Vladimir,MIDDLE,Ezreal,BOTTOM,Zilean,...,TOP,Amumu,JUNGLE,Syndra,MIDDLE,Jinx,BOTTOM,Milio,SUPPORT,1
8,NA1_4653552240,MonkeyKing,TOP,Vi,JUNGLE,Leblanc,MIDDLE,Zeri,BOTTOM,Janna,...,TOP,Khazix,JUNGLE,AurelionSol,MIDDLE,Lucian,BOTTOM,Amumu,SUPPORT,1
9,NA1_4652619790,Darius,TOP,Elise,JUNGLE,Ahri,MIDDLE,Ezreal,BOTTOM,Brand,...,TOP,Khazix,JUNGLE,Leblanc,MIDDLE,Jhin,BOTTOM,Sona,SUPPORT,0

In [27]:
import json
import csv
with open('13champs.json', 'r') as json_file:
    data = json.load(json_file)
id_dic = {}
data = data['data']
for i in data:
    id_dic[i] = data[i]['key']

print(id_dic)

{'Aatrox': '266', 'Ahri': '103', 'Akali': '84', 'Akshan': '166', 'Alistar': '12', 'Amumu': '32', 'Anivia': '34', 'Annie': '1', 'Aphelios': '523', 'Ashe': '22', 'AurelionSol': '136', 'Azir': '268', 'Bard': '432', 'Belveth': '200', 'Blitzcrank': '53', 'Brand': '63', 'Braum': '201', 'Caitlyn': '51', 'Camille': '164', 'Cassiopeia': '69', 'Chogath': '31', 'Corki': '42', 'Darius': '122', 'Diana': '131', 'Draven': '119', 'DrMundo': '36', 'Ekko': '245', 'Elise': '60', 'Evelynn': '28', 'Ezreal': '81', 'Fiddlesticks': '9', 'Fiora': '114', 'Fizz': '105', 'Galio': '3', 'Gangplank': '41', 'Garen': '86', 'Gnar': '150', 'Gragas': '79', 'Graves': '104', 'Gwen': '887', 'Hecarim': '120', 'Heimerdinger': '74', 'Illaoi': '420', 'Irelia': '39', 'Ivern': '427', 'Janna': '40', 'JarvanIV': '59', 'Jax': '24', 'Jayce': '126', 'Jhin': '202', 'Jinx': '222', 'Kaisa': '145', 'Kalista': '429', 'Karma': '43', 'Karthus': '30', 'Kassadin': '38', 'Katarina': '55', 'Kayle': '10', 'Kayn': '141', 'Kennen': '85', 'Khazix': '121', 'Kindred': '203', 'Kled': '240', 'KogMaw': '96', 'KSante': '897', 'Leblanc': '7', 'LeeSin': '64', 'Leona': '89', 'Lillia': '876', 'Lissandra': '127', 'Lucian': '236', 'Lulu': '117', 'Lux': '99', 'Malphite': '54', 'Malzahar': '90', 'Maokai': '57', 'MasterYi': '11', 'Milio': '902', 'MissFortune': '21', 'MonkeyKing': '62', 'Mordekaiser': '82', 'Morgana': '25', 'Nami': '267', 'Nasus': '75', 'Nautilus': '111', 'Neeko': '518', 'Nidalee': '76', 'Nilah': '895', 'Nocturne': '56', 'Nunu': '20', 'Olaf': '2', 'Orianna': '61', 'Ornn': '516', 'Pantheon': '80', 'Poppy': '78', 'Pyke': '555', 'Qiyana': '246', 'Quinn': '133', 'Rakan': '497', 'Rammus': '33', 'RekSai': '421', 'Rell': '526', 'Renata': '888', 'Renekton': '58', 'Rengar': '107', 'Riven': '92', 'Rumble': '68', 'Ryze': '13', 'Samira': '360', 'Sejuani': '113', 'Senna': '235', 'Seraphine': '147', 'Sett': '875', 'Shaco': '35', 'Shen': '98', 'Shyvana': '102', 'Singed': '27', 'Sion': '14', 'Sivir': '15', 'Skarner': '72', 'Sona': '37', 'Soraka': '16', 'Swain': '50', 'Sylas': '517', 'Syndra': '134', 'TahmKench': '223', 'Taliyah': '163', 'Talon': '91', 'Taric': '44', 'Teemo': '17', 'Thresh': '412', 'Tristana': '18', 'Trundle': '48', 'Tryndamere': '23', 'TwistedFate': '4', 'Twitch': '29', 'Udyr': '77', 'Urgot': '6', 'Varus': '110', 'Vayne': '67', 'Veigar': '45', 'Velkoz': '161', 'Vex': '711', 'Vi': '254', 'Viego': '234', 'Viktor': '112', 'Vladimir': '8', 'Volibear': '106', 'Warwick': '19', 'Xayah': '498', 'Xerath': '101', 'XinZhao': '5', 'Yasuo': '157', 'Yone': '777', 'Yorick': '83', 'Yuumi': '350', 'Zac': '154', 'Zed': '238', 'Zeri': '221', 'Ziggs': '115', 'Zilean': '26', 'Zoe': '142', 'Zyra': '143'}

In [28]:
name_id = pd.DataFrame(id_dic.items(), columns = ['champName', 'champId'])
name_id.to_csv('13names.csv', index = False)

## EACH Champion Winning Rate(table1)

In [29]:
# seperate to two team
newtable1 = df[['t1_champ1', 't1_champ2', 't1_champ3', 't1_champ4', 't1_champ5', 't1_win']]
newtable2 = df[['t2_champ1', 't2_champ2', 't2_champ3', 't2_champ4', 't2_champ5', 't1_win']]

newtable2['t1_win'] = newtable2['t1_win'].replace({0:1, 1:0})
# count winrate for team1
melttable = pd.melt(newtable1,id_vars=['t1_win'], var_name='player', value_name= 'champName')
melttable = melttable.dropna(subset=['t1_win'])
# count pick number
#melttable['champName'] = melttable['champName'].astype(int)
rolecount = melttable.groupby('champName').count()['t1_win']
# compute win count and win rate
wincount = melttable.groupby('champName').sum()['t1_win']
winpercent = wincount / rolecount
# final table for team1
result1 = pd.concat([rolecount, wincount, winpercent], axis = 1)
result1.columns = ['count', 'win', 'winpercent']

# same for table 2
melttable2 = pd.melt(newtable2,id_vars=['t1_win'], var_name='player', value_name= 'champName')

rolecount2 = melttable2.groupby('champName').count()['t1_win']
wincount2 = melttable2.groupby('champName').sum()['t1_win']
winpercent2 = wincount2 / rolecount2
result2 = pd.concat([rolecount2, wincount2, winpercent2],axis= 1)
result2.columns = ['count', 'win', 'winpercent']
# converge to one table
rolecount_total = rolecount + rolecount2
wincount_total = wincount + wincount2
winpercent_total = wincount_total / rolecount_total * 100

result = pd.concat([rolecount_total, wincount_total, winpercent_total], axis = 1)
result.columns = ['count', 'win', 'winpercent']

result.to_csv('13table1.csv', index = True)

/tmp/ipykernel_84/81144735.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newtable2['t1_win'] = newtable2['t1_win'].replace({0:1, 1:0})

In [30]:
# seperate to two team
newtable1 = df[['t1_champ1', 't1_champ2', 't1_champ3', 't1_champ4', 't1_champ5', 't1_win']]
newtable2 = df[['t2_champ1', 't2_champ2', 't2_champ3', 't2_champ4', 't2_champ5', 't1_win']]

newtable2['t1_win'] = newtable2['t1_win'].replace({0:1, 1:0})
# count winrate for team1
melttable = pd.melt(newtable1,id_vars=['t1_win'], var_name='player', value_name= 'champId')
print(melttable)

        t1_win     player    champId
0            1  t1_champ1       Yone
1            1  t1_champ1       Shen
2            0  t1_champ1    Camille
3            1  t1_champ1       Ornn
4            0  t1_champ1       Kled
...        ...        ...        ...
183060       0  t1_champ5      Janna
183061       0  t1_champ5    Alistar
183062       0  t1_champ5     Zilean
183063       0  t1_champ5      Milio
183064       0  t1_champ5  Seraphine

[183065 rows x 3 columns]
/tmp/ipykernel_84/1866249214.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newtable2['t1_win'] = newtable2['t1_win'].replace({0:1, 1:0})

In [31]:
df_1 = _deepnote_execute_sql('SELECT n.champName, n.champId, t.count, t.win, ROUND(t.winpercent,2) as winpercent\nFROM \'13names.csv\' as n, \'13table1.csv\' as t\nWHERE n.champName = t.champName\nORDER BY t.winpercent DESC', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_1

    champName  champId  count   win  winpercent
0         Zoe      142   1740   966       55.52
1     Kindred      203   2990  1637       54.75
2       Quinn      133    417   228       54.68
3      RekSai      421    869   471       54.20
4      Draven      119   3697  1997       54.02
..        ...      ...    ...   ...         ...
158   Sejuani      113    768   353       45.96
159    Illaoi      420   1060   484       45.66
160    Yorick       83    649   295       45.45
161    Renata      888    779   343       44.03
162     Corki       42    213    92       43.19

[163 rows x 5 columns]

In [32]:
df_1.to_csv('13table1_name.csv', index = False)
df_1.head(10)

      champName  champId  count   win  winpercent
0           Zoe      142   1740   966       55.52
1       Kindred      203   2990  1637       54.75
2         Quinn      133    417   228       54.68
3        RekSai      421    869   471       54.20
4        Draven      119   3697  1997       54.02
5       Skarner       72    649   348       53.62
6         Talon       91   2667  1426       53.47
7         Nilah      895   1186   632       53.29
8  Heimerdinger       74   1067   563       52.76
9         Annie        1   2505  1321       52.73

## Champion Combo win rate(table2)

In [12]:
# table only contain champion name and win or not
columns1 = {'t1_champ1': 't1p1_champId','t1_champ2': 't1p2_champId','t1_champ3': 't1p3_champId','t1_champ4': 't1p4_champId','t1_champ5': 't1p5_champId'}

columns2 = {'t2_champ1': 't2p1_champId','t2_champ2': 't2p2_champId','t2_champ3': 't2p3_champId','t2_champ4': 't2p4_champId','t2_champ5': 't2p5_champId'}


newtable1 = newtable1.rename(columns = columns1)
newtable2 = newtable2.rename(columns = columns2)
newtable1.to_csv('13team1.csv', index = False)
newtable2.to_csv('13team2.csv', index = False)

In [13]:
newtable2

      t2p1_champId t2p2_champId t2p3_champId t2p4_champId t2p5_champId  t1_win
0             Ornn     JarvanIV    Lissandra       Twitch        Rakan       0
1            Kayle         Udyr     Renekton       Lucian        Milio       0
2         Pantheon     JarvanIV       Syndra        Xayah        Milio       1
3             Sett      Kindred        Neeko        Ziggs       Thresh       0
4           Akshan       Khazix         Yone        Xayah       Xerath       1
...            ...          ...          ...          ...          ...     ...
36608   Tryndamere       LeeSin     Malzahar         Jinx        Rakan       1
36609         Kled      Kindred         Azir        Kaisa        Amumu       1
36610       Rengar       LeeSin        Corki        Sivir        Janna       1
36611   Tryndamere         Olaf         Ahri         Jinx       Thresh       1
36612        Riven         Ekko          Zed         Zeri        Rakan       1

[36613 rows x 6 columns]

In [14]:
df_2 = _deepnote_execute_sql('CREATE TABLE team1 (\n    player1 varchar,\n    player2 varchar,\n    t1_win int\n);\n\nINSERT INTO team1\nFROM (SELECT least(t1p1_champId, t1p2_champId) as small_champId,\n        greatest(t1p1_champId, t1p2_champId) as big_champId, t1_win\nFROM \'13team1.csv\' as player\nUNION ALL\nSELECT least(t1p1_champId, t1p3_champId) as small_champId,\n        greatest(t1p1_champId, t1p3_champId) as big_champId, t1_win\nFROM \'13team1.csv\' as player\nUNION ALL\nSELECT least(t1p1_champId, t1p4_champId) as small_champId,\n        greatest(t1p1_champId, t1p4_champId) as big_champId, t1_win\nFROM \'13team1.csv\' as player\nUNION ALL\nSELECT least(t1p1_champId, t1p5_champId) as small_champId,\n        greatest(t1p1_champId, t1p5_champId) as big_champId, t1_win\nFROM \'13team1.csv\' as player\nUNION ALL\nSELECT least(t1p2_champId, t1p3_champId) as small_champId,\n        greatest(t1p2_champId, t1p3_champId) as big_champId, t1_win\nFROM \'13team1.csv\' as player\nUNION ALL\nSELECT least(t1p2_champId, t1p4_champId) as small_champId,\n        greatest(t1p2_champId, t1p4_champId) as big_champId, t1_win\nFROM \'13team1.csv\' as player\nUNION ALL\nSELECT least(t1p2_champId, t1p5_champId) as small_champId,\n        greatest(t1p2_champId, t1p5_champId) as big_champId, t1_win\nFROM \'13team1.csv\' as player\nUNION ALL\nSELECT least(t1p3_champId, t1p4_champId) as small_champId,\n        greatest(t1p3_champId, t1p4_champId) as big_champId, t1_win\nFROM \'13team1.csv\' as player\nUNION ALL\nSELECT least(t1p3_champId, t1p5_champId) as small_champId,\n        greatest(t1p3_champId, t1p5_champId) as big_champId, t1_win\nFROM \'13team1.csv\' as player\nUNION ALL\nSELECT least(t1p4_champId, t1p5_champId) as small_champId,\n        greatest(t1p4_champId, t1p5_champId) as big_champId, t1_win\nFROM \'13team1.csv\' as player);\n\nSELECT *\nFROM (SELECT player1, player2, count(t1_win) as time, sum(t1_win) as win\nFROM team1 \nGROUP BY player1, player2\nORDER BY count(t1_win) DESC);', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_2

        player1  player2  time  win
0          Jinx    Milio   636  312
1         Rakan    Xayah   603  342
2          Jinx   Thresh   554  289
3      Aphelios   Thresh   494  260
4        Ezreal    Karma   410  190
...         ...      ...   ...  ...
12832      Jhin    Sivir     1    0
12833   Alistar    Rakan     1    1
12834    Renata    Urgot     1    1
12835  Malzahar  Orianna     1    1
12836     Braum    Rakan     1    1

[12837 rows x 4 columns]

In [15]:
df_3 = _deepnote_execute_sql('CREATE TABLE team2 (\n    player1 varchar,\n    player2 varchar,\n    t1_win int\n);\n\nINSERT INTO team2\nFROM (SELECT least(t2p1_champId, t2p2_champId) as small_champId,\n        greatest(t2p1_champId, t2p2_champId) as big_champId, t1_win\nFROM \'13team2.csv\' as player\nUNION ALL\nSELECT least(t2p1_champId, t2p3_champId) as small_champId,\n        greatest(t2p1_champId, t2p3_champId) as big_champId, t1_win\nFROM \'13team2.csv\' as player\nUNION ALL\nSELECT least(t2p1_champId, t2p4_champId) as small_champId,\n        greatest(t2p1_champId, t2p4_champId) as big_champId, t1_win\nFROM \'13team2.csv\' as player\nUNION ALL\nSELECT least(t2p1_champId, t2p5_champId) as small_champId,\n        greatest(t2p1_champId, t2p5_champId) as big_champId, t1_win\nFROM \'13team2.csv\' as player\nUNION ALL\nSELECT least(t2p2_champId, t2p3_champId) as small_champId,\n        greatest(t2p2_champId, t2p3_champId) as big_champId, t1_win\nFROM \'13team2.csv\' as player\nUNION ALL\nSELECT least(t2p2_champId, t2p4_champId) as small_champId,\n        greatest(t2p2_champId, t2p4_champId) as big_champId, t1_win\nFROM \'13team2.csv\' as player\nUNION ALL\nSELECT least(t2p2_champId, t2p5_champId) as small_champId,\n        greatest(t2p2_champId, t2p5_champId) as big_champId, t1_win\nFROM \'13team2.csv\' as player\nUNION ALL\nSELECT least(t2p3_champId, t2p4_champId) as small_champId,\n        greatest(t2p3_champId, t2p4_champId) as big_champId, t1_win\nFROM \'13team2.csv\' as player\nUNION ALL\nSELECT least(t2p3_champId, t2p5_champId) as small_champId,\n        greatest(t2p3_champId, t2p5_champId) as big_champId, t1_win\nFROM \'13team2.csv\' as player\nUNION ALL\nSELECT least(t2p4_champId, t2p5_champId) as small_champId,\n        greatest(t2p4_champId, t2p5_champId) as big_champId, t1_win\nFROM \'13team2.csv\' as player);\n\nSELECT *\nFROM (SELECT player1, player2, count(t1_win) as time, sum(t1_win) as win\nFROM team2 \nGROUP BY player1, player2\nORDER BY count(t1_win) DESC);\n', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_3

        player1 player2  time  win
0         Rakan   Xayah   671  363
1          Jinx   Milio   610  305
2      Aphelios  Thresh   522  271
3          Jinx  Thresh   513  272
4        Ezreal   Karma   427  214
...         ...     ...   ...  ...
12828   Alistar    Zyra     1    1
12829     Annie   Corki     1    1
12830      Ashe  Samira     1    0
12831   Alistar   Rakan     1    0
12832     Corki   Yasuo     1    1

[12833 rows x 4 columns]

In [16]:
df_4 = _deepnote_execute_sql('SELECT player1, player2, sum(time) as occurTime, sum(win) as winTime\nFROM (SELECT * FROM df_2\n    UNION ALL\n    SELECT * FROM df_3) as c2\nGROUP BY player1, player2\nORDER BY occurTime DESC', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_4

        player1 player2  occurTime  winTime
0         Rakan   Xayah       1274      705
1          Jinx   Milio       1246      617
2          Jinx  Thresh       1067      561
3      Aphelios  Thresh       1016      531
4        Ezreal   Karma        837      404
...         ...     ...        ...      ...
13031     Braum    Lulu          1        1
13032     Milio  Thresh          1        0
13033  Kassadin  Qiyana          1        1
13034     Brand    Zyra          1        0
13035   Caitlyn   Sivir          1        1

[13036 rows x 4 columns]

In [17]:
# save to csv file
df_4.to_csv('13table2.csv', index = False)

In [18]:
df_5 = _deepnote_execute_sql('SELECT m.champName as champName1, m.champId as champId1, n.champName as champName2, n.champId as champId2, c.occurTime, c.winTime\nFROM df_4 as c, \'13names.csv\' as m, \'13names.csv\' as n\nWHERE m.champName = c.player1 and n.champName = c.player2', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_5

      champName1  champId1 champName2  champId2  occurTime  winTime
0          Rakan       497      Xayah       498       1274      705
1           Jinx       222      Milio       902       1246      617
2           Jinx       222     Thresh       412       1067      561
3       Aphelios       523     Thresh       412       1016      531
4         Ezreal        81      Karma        43        837      404
...          ...       ...        ...       ...        ...      ...
13031     Samira       360      Xayah       498          1        0
13032    Nidalee        76    Skarner        72          1        0
13033      Galio         3       Ryze        13          1        0
13034     Rammus        33         Vi       254          3        1
13035     Draven       119     Samira       360          1        0

[13036 rows x 6 columns]

In [19]:
# save the file to csv
df_5.to_csv('13table2_name.csv', index = False)
df_5.head(10)

  champName1  champId1 champName2  champId2  occurTime  winTime
0      Rakan       497      Xayah       498       1274      705
1       Jinx       222      Milio       902       1246      617
2       Jinx       222     Thresh       412       1067      561
3   Aphelios       523     Thresh       412       1016      531
4     Ezreal        81      Karma        43        837      404
5       Jinx       222       Lulu       117        719      352
6      Yuumi       350       Zeri       221        671      339
7       Jinx       222     Khazix       121        633      320
8     Lucian       236      Milio       902        633      336
9     Ezreal        81     Khazix       121        616      308

## Champion in a different position(table3)

In [31]:
positions = ['SUPPORT', 'ADC', 'MIDDLE', 'JUNGLE', 'TOP']


# Team 1
t1_fields = []

for position in range(1, 6):
    field = f't1p{position}_champId'
    t1_fields.append(field)

t1 = df[t1_fields].copy()
t1['t1_win'] = df['t1_win']
t1 = t1.melt(id_vars=['t1_win'], value_vars=t1_fields[:], var_name='position', value_name='champId')
t1['position'] = t1['position'].replace(dict(zip(t1_fields, positions)))
t1 = t1.groupby(['position', 'champId']).agg({'t1_win': ['count', 'sum', 'mean']})
t1.columns = ['appearances', 'wins', 'winrate']
t1 = t1.reset_index()


# Team 2
t2_fields = []

for position in range(1, 6):
    field = f't2p{position}_champId'
    t2_fields.append(field)

t2 = df[t2_fields].copy()
t2['t2_win'] = df['t1_win'].replace({0: 1, 1: 0})
t2 = t2.melt(id_vars=['t2_win'], value_vars=t2_fields[:], var_name='position', value_name='champId')
t2['position'] = t2['position'].replace(dict(zip(t2_fields, positions)))
t2 = t2.groupby(['position', 'champId']).agg({'t2_win': ['count', 'sum', 'mean']})
t2.columns = ['appearances', 'wins', 'winrate']
t2 = t2.reset_index()

In [41]:
# Merge
merged_table = pd.merge(t1, t2, on=['position', 'champId'], how='outer')
merged_table = merged_table.fillna(0)
merged_table['appearances'] = merged_table['appearances_x'].add(merged_table['appearances_y'])
merged_table['wins'] = merged_table['wins_x'].add(merged_table['wins_y'])
merged_table = merged_table.drop(columns=['appearances_x', 'appearances_y', 'wins_x', 'wins_y', 'winrate_x', 'winrate_y'])
merged_table['winrate'] = merged_table['wins'] / merged_table['appearances']
pivot_table = merged_table.pivot_table(index='champId', 
                                        columns='position', 
                                        values=['appearances', 'wins', 'winrate'],
                                        aggfunc='sum')
pivot_table.columns = ['_'.join(reversed(col)).strip() for col in pivot_table.columns.values]
pivot_table = pivot_table.sort_index(axis=1)
pivot_table = pivot_table.reset_index()
pivot_table.to_csv('table3.csv', index = False)

In [37]:
df_6 = _deepnote_execute_sql('SELECT n.champName, t.*\nFROM \'names.csv\' as n, \'table3.csv\' as t\nWHERE t.champId = n.champId\n', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_6

,champName,champId,ADC_appearances,ADC_winrate,ADC_wins,JUNGLE_appearances,JUNGLE_winrate,JUNGLE_wins,MIDDLE_appearances,MIDDLE_winrate,MIDDLE_wins,SUPPORT_appearances,SUPPORT_winrate,SUPPORT_wins,TOP_appearances,TOP_winrate,TOP_wins
0,Annie,1,26.0,0.576923,15.0,2.0,1.000000,2.0,856.0,0.556075,476.0,42.0,0.404762,17.0,82.0,0.536585,44.0
1,Olaf,2,27.0,0.518519,14.0,2798.0,0.515011,1441.0,41.0,0.365854,15.0,1.0,1.000000,1.0,600.0,0.515000,309.0
2,Galio,3,19.0,0.526316,10.0,8.0,0.375000,3.0,5680.0,0.530810,3015.0,732.0,0.513661,376.0,126.0,0.595238,75.0
3,TwistedFate,4,2.0,0.500000,1.0,1.0,0.000000,0.0,4164.0,0.500240,2083.0,5.0,0.400000,2.0,32.0,0.437500,14.0
4,XinZhao,5,NaN,NaN,NaN,454.0,0.517621,235.0,8.0,0.750000,6.0,NaN,NaN,NaN,6.0,0.500000,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,Draven,119,2852.0,0.515077,1469.0,1.0,0.000000,0.0,20.0,0.500000,10.0,NaN,NaN,NaN,10.0,0.400000,4.0
146,Lissandra,127,NaN,NaN,NaN,NaN,NaN,NaN,605.0,0.462810,280.0,2.0,0.500000,1.0,24.0,0.416667,10.0
147,Aatrox,266,2.0,0.500000,1.0,33.0,0.363636,12.0,182.0,0.434066,79.0,1.0,0.000000,0.0,1896.0,0.462025,876.0
148,Kalista,429,3594.0,0.500556,1799.0,4.0,0.250000,1.0,94.0,0.404255,38.0,NaN,NaN,NaN,177.0,0.457627,81.0
149,Aphelios,523,2952.0,0.475271,1403.0,NaN,NaN,NaN,3.0,0.333333,1.0,1.0,0.000000,0.0,2.0,0.500000,1.0

In [40]:
df_6.to_csv('table3_n.csv', index = False)
df_6.head(10)

,champName,champId,ADC_appearances,ADC_winrate,ADC_wins,JUNGLE_appearances,JUNGLE_winrate,JUNGLE_wins,MIDDLE_appearances,MIDDLE_winrate,MIDDLE_wins,SUPPORT_appearances,SUPPORT_winrate,SUPPORT_wins,TOP_appearances,TOP_winrate,TOP_wins
0,Annie,1,26.0,0.576923,15.0,2.0,1.000000,2.0,856.0,0.556075,476.0,42.0,0.404762,17.0,82.0,0.536585,44.0
1,Olaf,2,27.0,0.518519,14.0,2798.0,0.515011,1441.0,41.0,0.365854,15.0,1.0,1.000000,1.0,600.0,0.515000,309.0
2,Galio,3,19.0,0.526316,10.0,8.0,0.375000,3.0,5680.0,0.530810,3015.0,732.0,0.513661,376.0,126.0,0.595238,75.0
3,TwistedFate,4,2.0,0.500000,1.0,1.0,0.000000,0.0,4164.0,0.500240,2083.0,5.0,0.400000,2.0,32.0,0.437500,14.0
4,XinZhao,5,NaN,NaN,NaN,454.0,0.517621,235.0,8.0,0.750000,6.0,NaN,NaN,NaN,6.0,0.500000,3.0
5,Urgot,6,NaN,NaN,NaN,5.0,0.600000,3.0,49.0,0.571429,28.0,NaN,NaN,NaN,1663.0,0.514732,856.0
6,Leblanc,7,3.0,0.333333,1.0,NaN,NaN,NaN,3180.0,0.480189,1527.0,4.0,0.250000,1.0,20.0,0.550000,11.0
7,Vladimir,8,35.0,0.485714,17.0,2.0,0.000000,0.0,1071.0,0.495798,531.0,2.0,0.000000,0.0,1957.0,0.500255,979.0
8,Fiddlesticks,9,NaN,NaN,NaN,1463.0,0.530417,776.0,22.0,0.545455,12.0,259.0,0.451737,117.0,5.0,0.400000,2.0
9,Kayle,10,2.0,0.500000,1.0,NaN,NaN,NaN,76.0,0.526316,40.0,20.0,0.500000,10.0,598.0,0.458194,274.0

## Champion Ban & win rate(table5)

In [44]:
team1 = df[['t1p1_ban_champId', 't1p2_ban_champId', 't1p3_ban_champId', 't1p4_ban_champId', 't1p5_ban_champId']]
team2 = df[['t2p1_ban_champId', 't2p2_ban_champId', 't2p3_ban_champId', 't2p4_ban_champId', 't2p5_ban_champId']]
# Combine with result
teamPlus = df[['t1p1_ban_champId', 't1p2_ban_champId', 't1p3_ban_champId', 't1p4_ban_champId', 't1p5_ban_champId', 't2p1_ban_champId', 't2p2_ban_champId', 't2p3_ban_champId', 't2p4_ban_champId', 't2p5_ban_champId', 't1_win']]
# select rows where values in column  
team1Lose = teamPlus[teamPlus['t1_win'] == 0]
# drop column
team1Lose = team1Lose.drop(columns=['t1_win'])
# select rows where values in column  
team1Win = teamPlus[teamPlus['t1_win'] == 1]
team1Win = team1Win.drop(columns=['t1_win'])


# count the occurrences of all values in the DataFrame
all_countsT1 = pd.Series(team1.values.flatten()).value_counts()

# display the resulting counts
# create a new DataFrame from the counts Series
counts_dfT1 = pd.DataFrame({'hero': all_countsT1.index, 'count': all_countsT1.values})

# sort the DataFrame by values in column 'A' in ascending order
df_sortedT1 = counts_dfT1.sort_values(by='hero', ascending=True)

# reset the index to a new sequential index
finalT1 = df_sortedT1.reset_index(drop=True)

##################################################################################################

all_countsT2 = pd.Series(team2.values.flatten()).value_counts()
counts_dfT2 = pd.DataFrame({'hero': all_countsT2.index, 'count': all_countsT2.values})
df_sortedT2 = counts_dfT2.sort_values(by='hero', ascending=True)
finalT2 = df_sortedT2.reset_index(drop=True)

concatenated_df = pd.concat([finalT1, finalT2])

grouped_df = concatenated_df.groupby('hero')['count'].sum().reset_index()
# change the column name of column
subFinal = grouped_df.rename(columns={'count': 'totalCount'})

##################################################################################################

# count the occurrences of all values in the DataFrame
all_countsZ = pd.Series(team1Lose.values.flatten()).value_counts()

# display the resulting counts
# create a new DataFrame from the counts Series
counts_dfZ = pd.DataFrame({'hero': all_countsZ.index, 'count': all_countsZ.values})

# sort the DataFrame by values in column 'A' in ascending order
df_sortedZ = counts_dfZ.sort_values(by='hero', ascending=True)

# reset the index to a new sequential index
finalZ = df_sortedZ.reset_index(drop=True)
# merge the two DataFrames on column 'A'
merged_df = pd.merge(subFinal, finalZ, on='hero')

# count the occurrences of all values in the DataFrame
all_countsO = pd.Series(team1Win.values.flatten()).value_counts()

# display the resulting counts
# create a new DataFrame from the counts Series
counts_dfO = pd.DataFrame({'hero': all_countsO.index, 'count': all_countsO.values})

# sort the DataFrame by values in column 'A' in ascending order
df_sortedO = counts_dfO.sort_values(by='hero', ascending=True)

# reset the index to a new sequential index
finalO = df_sortedO.reset_index(drop=True)

# merge the two DataFrames on column 'A'
mergedF = pd.merge(merged_df, finalO, on='hero')
mergedF = mergedF.rename(columns={'count_x': 'team1Lose', 'count_y': 'team1Win'})
mergedF = mergedF.sort_values(by='totalCount', ascending=False)
mergedF = mergedF.reset_index(drop=True)

mergedF.to_csv('table5.csv', index = False)
mergedF.head(10)

   hero  totalCount  team1Lose  team1Win
0    51       50181      25002     25179
1    30       35124      17367     17757
2   777       34274      16990     17284
3    -1       26559      13421     13138
4    76       24838      12356     12482
5   104       20590      10222     10368
6    28       17799       8760      9039
7    38       16039       7963      8076
8    80       15953       7920      8033
9   121       15906       7811      8095

## Final champion data

In [46]:
df_7 = _deepnote_execute_sql('SELECT t1.*, t5.totalCount as BanTime, t2.position_1 as max_position, t2.appearance_1 as max_appearance, t2.position_2 as second_position, t2.appearance_2 as second_appearance\nFrom \'table1_name.csv\' as t1, \'table5.csv\' as t5, \'top_two_positions.csv\' as t2\nWHERE t1.champId =  t5.hero and t2.champId = t1.champId', 'SQL_DEEPNOTE_DATAFRAME_SQL', audit_sql_comment='', sql_cache_mode='cache_disabled')
df_7

,champName,champId,count,win,winpercent,BanTime,max_position,max_appearance,second_position,second_appearance
0,TwistedFate,4,4204,2100,0.500,3255,MIDDLE,4164,TOP,32.0
1,XinZhao,5,468,244,0.521,47,JUNGLE,454,MIDDLE,8.0
2,Leblanc,7,3207,1540,0.480,6405,MIDDLE,3180,TOP,20.0
3,Teemo,17,762,396,0.520,185,TOP,669,MIDDLE,42.0
4,Warwick,19,699,353,0.505,116,JUNGLE,495,TOP,161.0
...,...,...,...,...,...,...,...,...,...,...
145,Veigar,45,1504,753,0.501,217,ADC,831,MIDDLE,561.0
146,Kennen,85,2720,1403,0.516,1557,TOP,2397,MIDDLE,281.0
147,Kled,240,1054,539,0.511,239,TOP,881,MIDDLE,158.0
148,Ryze,13,1387,703,0.507,51,MIDDLE,1093,TOP,290.0
149,Darius,122,2239,1148,0.513,7766,TOP,2180,MIDDLE,39.0

In [49]:
df_7.fillna(0)
df_7.to_csv('final_table.csv', index = False)
df_7.head(10)

,champName,champId,count,win,winpercent,BanTime,max_position,max_appearance,second_position,second_appearance
0,TwistedFate,4,4204,2100,0.500,3255,MIDDLE,4164,TOP,32.0
1,XinZhao,5,468,244,0.521,47,JUNGLE,454,MIDDLE,8.0
2,Leblanc,7,3207,1540,0.480,6405,MIDDLE,3180,TOP,20.0
3,Teemo,17,762,396,0.520,185,TOP,669,MIDDLE,42.0
4,Warwick,19,699,353,0.505,116,JUNGLE,495,TOP,161.0
5,MissFortune,21,2207,1063,0.482,36,ADC,2172,SUPPORT,28.0
6,Twitch,29,1456,720,0.495,335,ADC,1368,JUNGLE,75.0
7,Karthus,30,6971,3708,0.532,35124,JUNGLE,4996,ADC,1294.0
8,Amumu,32,232,104,0.448,234,JUNGLE,219,SUPPORT,7.0
9,Rammus,33,467,216,0.463,224,TOP,224,JUNGLE,175.0

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=e55512df-58ef-402e-8f63-17a773fe09fc' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>